### ISSUE TITLE
MSSQL Error getting database tables and views

### ISSUE THREAD

**Issue by bigboss97lnt** [widestage/widestage#106] opened 2020-05-08 02:09 UTC
Just started using widestage and the following error occurs when trying to open DB's tables from layers option:
**Error getting database tables and views : RequestError: 'CONCAT' is not a recognized built-in function name.**

Does it have a fix or a workaround? 
Thanks,

Nasser

![image](https://user-images.githubusercontent.com/64983216/81362477-a51ad400-90e9-11ea-808b-00db47f36b8f.png)
![image](https://user-images.githubusercontent.com/64983216/81362596-df847100-90e9-11ea-8387-c44c0eb1091f.png)

**Comment by othman-fayed** [comment] 2020-05-18 22:49
Where you able to resolve this matter? I'm getting an error too.

**Comment by bigboss97lnt** [comment] 2020-05-19 00:25
negative

**Comment by othman-fayed** [comment] 2020-05-19 19:01
I fixed, the code mssql.js, internalQuery function
You need to return resultset.resultset instead of resultset.
Refer to the query method in the class to see what i mean.

**Comment by beevou** [comment] 2020-06-07 07:29
Sorry, we are not able to reproduce the error, what SLL Server version are you working with?

**Comment by beevou** [comment] 2020-06-18 08:40
Hey @bigboss97lnt , any progress on this?

**Comment by bigboss97lnt** [comment] 2020-06-18 12:48
I’m using it with MySQL connections and Queries and its working fine with me, didn’t try connecting to SQL Server again but I would love to! 
@othman-fayed if you fixed the SQL issue please provide detailed instructions! That would be great :D! Thanks indeed
Nasser

**Comment by othman-fayed** [comment] 2020-06-20 03:22
The issue was fixed by the recent commit 'connection fix' so it should be resolved

**Closed** 2020-09-24 06:55 UTC
